# Generated by Django 4.2.6 on 2023-10-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emai',
            new_name='email',
        ),
    ]
